### ISSUE TITLE
The email address

### ISSUE THREAD

**Issue by xjwla** [lordmartian/deep_avsr#17]
Hi,
Thank you for your open-source code. I want to send an email at `smeetrs<AT>iitb.ac.in`  for the pre-trained weights of the AO, VO and AV models. But  the email address keeps showing errors.

**Comment by lordmartian** [comment]
Hi,
I myself tried sending an email on that address from an another email id and I didn't face any problems. Also I received an email for pretrained weights on the same id after this issue was opened. Please try again and check if the problem persists. Be sure to replace <AT> with @. If it still doesn't work, there may be some issue at your end.
