### ISSUE TITLE
Out of Memory errors during pretraining

### ISSUE THREAD

**Issue by kasri-mids** [lordmartian/deep_avsr#3]
I seem to hit OOM errors as I proceed into pretraining steps/epochs. The memory footprint keeps increasing after each step/epoch. I would have expected it to remain constant for each step/epoch. Am I wrong?

The memory footprint was around ~9G when pretraining started and has steadily increased since.
```
top - 20:43:22 up 10:22,  1 user,  load average: 2.15, 2.53, 2.41
Tasks: 353 total,   2 running, 268 sleeping,   0 stopped,   0 zombie
%Cpu(s):  8.8 us,  3.3 sy,  0.0 ni, 86.6 id,  1.2 wa,  0.0 hi,  0.1 si,  0.0 st
KiB Mem : 16368460 total,   190368 free, **13370028 used**,  2808064 buff/cache
KiB Swap:  6291452 total,  4440572 free,  1850880 used.  2390908 avail Mem 
```

A couple of steps later
```
top - 20:44:38 up 10:23,  1 user,  load average: 1.63, 2.29, 2.33
Tasks: 352 total,   2 running, 268 sleeping,   0 stopped,   0 zombie
%Cpu(s):  9.1 us,  3.3 sy,  0.0 ni, 86.2 id,  1.4 wa,  0.0 hi,  0.1 si,  0.0 st
KiB Mem : 16368460 total,   159724 free, **13424752** used,  2783984 buff/cache
KiB Swap:  6291452 total,  4431356 free,  1860096 used.  2333444 avail Mem 

```

Is this increase expected or does something need to be re-initialized?

**Comment by LordMartian** [comment]
This is expected since the size of each mini-batch varies because of varying sequence lengths. The memory footprint will be almost constant once the longest of the sequences have been seen. Also, you may need to reduce the mini-batch size for the latter iterations of curriculum learning where the value of NUM_WORDS is more.

Also, since you are training from scratch, it would be helpful to train the audio-only and video-only models first and then use them to initialize the encoders of the audio-visual model.

**Comment by kasri-mids** [comment]
Thanks for the response.
I am doing video only as you recommend above. Using a mini batch of 8 for NUM_WORDS=5. The memory footprint starts at 4GB and is at ~8GB and rising (after 120 steps). It seems to be linearly increasing and seems inevitable that this is going to crash in some time. What makes the size increase step over step? What is being saved/appended to a variable?

Also, I notice that the config file has 16384 samples per step. You call this the virtual epoch. The lrs2 pretrain dataset has 96318 samples. So should I replace the 16384  with maybe 65536 (2^16). So will each epoch then randomly select 2^16 videos for training?

**Comment by LordMartian** [comment]
I had trained the model using a GPU with 11GB memory and I was able to train the model with a minibatch size of 32 for NUM_WORDS=5. So are you doing something different or have you changed anything? For me, the memory used to increase initially but then after a certain number of steps, it used to be almost constant. 

Nothing gets added or appended during training. I had tried to search the reason for this memory usage increase, but most answers pointed to it being the variable sized batches and the way pytorch deals with them. I will keep this issue open so that if anyone in future has any solution, he/she can add it here. In the meantime, you can try the following code to clear the unallocated memory. Add it either after processing of every minibatch (in `utils/general.py`) or after every step (in `pretrain.py`).

```
if torch.cuda.is_available():
    torch.cuda.empty_cache()
```

You can certainly vary the number of samples in a step. The samples will be selected randomly. However, the values of scheduler hyperparameters, save_frequency etc., will have to be tweaked as well.

**Comment by LordMartian** [comment]
@kasri-mids is this issue solved?

**Comment by kasri-mids** [comment]
This issue persists but gets masked when using a bigger RAM machine. The
memory issue is not on the GPU but system RAM

**Comment by LordMartian** [comment]
I misunderstood it for the GPU memory. Sorry about that. Does the training terminate if at all the system RAM gets filled up?

I didn't face this issue so I can't say for certain but you can try reducing the NUM_WORKERS to either 4 or 2 and see whether that helps.

**Comment by devanshbatra04** [comment]
@lordmartian 
Is there a memory leak in preprocessing? I am trying to use the network on LRS3. Preprocessing the dataset gives me similar cuda out of memory error. I tried to monitor the usage. It starts at around 1 GB and soon increases to 4 GB after about 2500 videos/iterations. I have a 11 GB GPU.

**Comment by lordmartian** [comment]
You can check the preprocessing code in `audio_visual/utils/preprocessing.py`. The only part which uses CUDA is where the visual frontend is used to extract the visual features from the sample videos. As per my knowledge, it should not cause any memory leaks. For LRS2, there is a pretrain set and a main set. As per my experience, when the code is processing the main set, the memory usage is low but it increases when it starts processing the pretrain set. This is due to the larger duration of video clips in the pretrain set. I haven't worked with LRS3 and am unaware of its structure and other stats. Can you please tell me what is the length of the longest clip in LRS3? Also, what is the size of the frames and whether you are using RGB frames or greyscale (of the input to the visual frontend)? It is possible that some clips may be quite large that they may not be fitting in the available memory. Also, you can try to use this code block after processing of each sample to clear up the memory and see if it helps:
```
if torch.cuda.is_available():
    torch.cuda.empty_cache()
```
Please let me know.

**Comment by devanshbatra04** [comment]
Hi @lordmartian 
Thanks for replying I had tried the `torch.cuda.empty_cache()` function call but to no avail. It is likely due to large video size itself. 
LRS3 has pretrain, trainval and test suites.The biggest video is 11 minutes and 74 MB. I am using RGB frames. 

I will try filtering out all videos greater than 10 MB. Thank you!

**Comment by arunm95** [comment]
@lordmartian I am running into the GPU memory allocation error while pretraining. I'm also on an 11gb GPU. Initially dropping the batch size to 16 and then to 8 worked, but at 29 words, the error happens regardless of dataloader number or batch size.

**Comment by lordmartian** [comment]
@arunm95 Are you getting the error while training AV model? If so, are you keeping the encoder weights fixed?

**Comment by arunm95** [comment]
I'm getting it while training the AO model

**Comment by lordmartian** [comment]
Can you please provide the error log, the OS you are using, the values of dataloader num workers and batch size that you tried and any other changes that you have made? 
Also at 29 words, almost full 11 GB memory is used. So are you certain that no other processes were using the GPU while you were training?

**Comment by BaiXue333** [comment]
Hi @lordmartian, I had the same problem as @kasri-mids. In VO pretrain, I had trained the model using a GPU with 11GB memory and trained the model with a minibatch size of 32 for NUM_WORDS=5. But I hit OOM at the 120 epoch. I also adjusted the minibatch into 16, but it didn't work. 
Why does such a problem occur under the same conditions?

**Comment by lordmartian** [comment]
@BaiXue333 I think @kasri-mids was facing the issue on system RAM and not on GPU. 
Did you try using the `empty_cache()` function given in one of the above comments? Also, you can try with minibatch size 8 and see if the issue persists.

**Comment by BaiXue333** [comment]
@lordmartian I didn't use `empty_cache()` function. But I tried with smaller minibatch size and it worked. Can you provide the batchsize you used for every NUM_WORD?

Besides, I have tried `Data Parallel`  and `Distributed Data Parallel` to use more GPUs. DP and DPP can support larger batchsize and accelerate training.

In `Pretrain` ,  I have trained the model using DDP for NUM_WORDS=29,37. Finally I get AO wer 26.0% and VO wer 79.4 % and the results look worse than yours. I am currently testing the difference between a single card and multiple cards.

**Comment by BaiXue333** [comment]
@lordmartian I didn't use empty_cache() function. But I tried with smaller minibatch size and it worked. Can you provide the batchsize you used for every NUM_WORD?

Besides, I have tried Data Parallel and Distributed Data Parallel to use more GPUs. DP and DPP can support larger batchsize and accelerate training.

In Pretrain , I have trained the model using DDP for NUM_WORDS=29,37. Finally I get AO wer 26.0% and VO wer 79.4 % and the results look worse than yours. I am currently testing the difference between a single GPU and multiple GPUs.

**Comment by BaiXue333** [comment]
@lordmartian I didn't use `empty_cache()` function. But I tried with smaller minibatch size and it worked. Can you provide the batchsize you used for every `NUM_WORD`?

Besides, I have tried `Data Parallel` and `Distributed Data Parallel` to use more GPUs. DP and DPP can support larger batchsize and accelerate training.

In Pretrain , I have trained the model using DDP for `NUM_WORDS`=29,37. Finally I get AO wer 26.0% and VO wer 79.4 % and the results look worse than yours. I am currently testing the difference between a single GPU and multiple GPUs.

**Comment by lordmartian** [comment]
> Can you provide the batchsize you used for every `NUM_WORD`?

Unfortunately, I don't have this data.

Your WER values are very close to what I obtained. You can them here:
https://github.com/lordmartian/deep_avsr/issues/8#issuecomment-695196122

**Comment by BaiXue333** [comment]
Hi, @lordmartian I finished the AO and VO steps. The WER values are close to yours.

| Model | After pretraining | After training |
| ------------ | -----------| ------------ |
AO | 0.260 | 0.180
VO | 0.797 | 0.697

Besides, You metion that `We then initialize the AV model with weights from the trained AO and VO models as follows: AO Audio Encoder → AV Audio Encoder, VO Video Encoder → AV Video Encoder, VO Video Decoder → AV Joint Decoder.`  Is the trained AO/VO  models means pretrained AO/VO models or trained (train with training set) AO/VO models?

**Comment by lordmartian** [comment]
@BaiXue333 Use pretrained models.
